Repository gardener/connectivity-exporter, pull requests merged in 2021-11, with the labels that each got.

#2 Refactor deploy script
  README.md
  hack/deploy-to-seed.sh
  hack/deploy-to-shoot.sh
  hack/deploy.sh
Labels: needs/review, size/s

#1 CI: initial GitHub Action
  .github/workflows/build.yml
  connectivity-exporter/packet/bpf_test.go
Labels: reviewed/lgtm, size/m

#4 connectivity-exporter: add CLI flag -metrics-addr
  connectivity-exporter/main.go
  connectivity-exporter/metrics/metrics.go
Labels: needs/review, size/xs

#3 connectivity-exporter: monitoring all interfaces
  connectivity-exporter/packet/bpf.go
Labels: needs/review, size/xs

#6 Add pprof for debugging
  connectivity-exporter/main.go
Labels: needs/review, size/xs

#5 build: container images and helm charts
  .github/workflows/build.yml
  charts/connectivity-monitor/Chart.yaml
  charts/connectivity-monitor/templates/ds.yaml
  charts/connectivity-monitor/templates/rbac.yaml
  charts/connectivity-monitor/values.yaml
  connectivity-exporter/Dockerfile
  connectivity-exporter/Makefile
Labels: reviewed/lgtm, size/m

#7 Action format
  .github/workflows/build.yml
  connectivity-exporter/internal/tools/tools.go
  connectivity-exporter/packet/bpf_prod.go
  connectivity-exporter/packet/bpf_testing.go
Labels: needs/review, size/xs
