Repository gardener/connectivity-exporter, pull requests merged in 2022-05, with the labels that each got.

#19 Error budget dashboards
  charts/connectivity-monitor/dashboards/cpu-and-memory-usage.json
  charts/connectivity-monitor/dashboards/error-budget.json
  charts/connectivity-monitor/dashboards/failed-seconds.json
  charts/connectivity-monitor/dashboards/golang-metrics.json
  charts/connectivity-monitor/dashboards/home.json
  charts/connectivity-monitor/dashboards/memory-stat.json
  charts/connectivity-monitor/dashboards/tracking.json
  charts/connectivity-monitor/dashboards/uptime-overview.json
  charts/connectivity-monitor/dashboards/uptime.json
  charts/connectivity-monitor/rules/error-budget.yaml
  charts/connectivity-monitor/templates/ds.yaml
  charts/connectivity-monitor/templates/monitoring.yaml
  connectivity-exporter/Makefile
Labels: needs/second-opinion, size/xl

#20 Fix an issue where the metrics did not get reapplied
  connectivity-exporter/metrics/metrics.go
  connectivity-exporter/metrics/types.go
  connectivity-exporter/packet/packet.go
Labels: reviewed/lgtm, size/xs

#21 Increase the TTL to 15 minutes
  connectivity-exporter/metrics/types.go
Labels: needs/review, size/xs

#23 Cleanup
  charts/connectivity-exporter/Chart.yaml
  charts/connectivity-exporter/dashboards/uptime-overview.json
  charts/connectivity-exporter/dashboards/uptime.json
  charts/connectivity-exporter/rules/error-budget.yaml
  charts/connectivity-exporter/templates/ds.yaml
  charts/connectivity-exporter/templates/monitoring.yaml
  charts/connectivity-exporter/templates/recordingrules.yaml
  charts/connectivity-exporter/values.yaml
  charts/connectivity-monitor/Chart.yaml
  docs/localsetup.md
  hack/connectivity-exporter/down.sh
  hack/connectivity-exporter/up-gardener.sh
  hack/connectivity-exporter/up.sh
  hack/export-dashboards.sh
Labels: needs/review, size/s

#28 Add some panels to show the cluster downtimes in seconds
  charts/connectivity-exporter/dashboards/uptime.json
Labels: needs/review, needs/second-opinion, size/l

#27 Increase the rule evaluation interval to 30s
  charts/connectivity-exporter/rules/error-budget.yaml
Labels: needs/review, size/xs

#29 Add an sni regex filter to the uptime overview dashboard
  charts/connectivity-exporter/dashboards/uptime-overview.json
Labels: reviewed/lgtm, size/s

#30 Reset the weekly metrics on Sundays at midnight
  charts/connectivity-exporter/rules/error-budget.yaml
Labels: needs/review, size/xs
